Repository SECQUOIA/gdplib, pull requests merged in 2024-05, with the labels that each got.

#15 Logical-spectralog
  gdplib/logical/spectralog.py
Labels: documentation

#18 Refactor and update heat integration models
  gdplib/mod_hens/cafaro_approx.py
  gdplib/mod_hens/common.py
  gdplib/mod_hens/conventional.py
  gdplib/mod_hens/modular_discrete.py
  gdplib/mod_hens/modular_discrete_single_module.py
  gdplib/mod_hens/modular_integer.py
Labels: documentation, question

#19 Refactor alphanumeric sorting functions and update documentation
  gdplib/stranded_gas/model.py
  gdplib/stranded_gas/util.py
Labels: documentation, ready to merge

#16 Syngas Documentation
  gdplib/syngas/syngas_adapted.py
Labels: documentation

#17 Update documentation for supply and demand constraints in biofuel model
  gdplib/biofuel/model.py
Labels: documentation, ready to merge

#21 Benchmark code with the result example of jobshop
  .gitignore
  benchmark.py
  gdplib/__init__.py
  gdplib/batch_processing/__init__.py
  gdplib/batch_processing/batch_processing.dat
  gdplib/batch_processing/batch_processing.py
  gdplib/disease_model/__init__.py
  gdplib/disease_model/disease_model.py
  gdplib/jobshop/__init__.py
  gdplib/jobshop/jobshop-small.dat
  gdplib/jobshop/jobshop.py
  gdplib/med_term_purchasing/__init__.py
  gdplib/med_term_purchasing/med_term_purchasing.dat
  gdplib/med_term_purchasing/med_term_purchasing.py
  gdplib/pyomo_examples/README.md
  gdplib/pyomo_examples/__init__.py
  gdplib/pyomo_examples/disease_model.py
  generate_model_size_report.py
Labels: ready to merge

#22 Add github Lint workflow
  .github/workflows/lint.yml
Labels: ready to merge

#24 Add documentation for distillation column model
  .github/workflows/lint.yml
  gdplib/gdp_col/column.py
  gdplib/gdp_col/fenske.py
  gdplib/gdp_col/initialize.py
  gdplib/gdp_col/main.py
Labels: documentation

#28 Reactor_series
  gdplib/cstr/README.md
  gdplib/cstr/gdp_reactor.py
Labels: documentation
